name: form_mobx
description: Form with Validation in MobX

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.2
  flutter_mobx: ^2.0.6+1
  mobx: ^2.0.7+5
  validators2: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_lints: ^2.0.0
  mobx_codegen: ^2.0.7
  build_runner: ^2.2.0

flutter:

  uses-material-design: true

  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
